services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - db
    networks:
      - app-network
  
  consolechat:
    container_name: consolechat
    image: ${DOCKER_REGISTRY-}consolechat
    build:
      context: .
      dockerfile: CONSOLECHAT/Dockerfile
    depends_on:
      - mcp
    networks:
      - app-network
    stdin_open: true 
    tty: true         

  mcp:
    container_name: mcp
    image: ${DOCKER_REGISTRY-}mcp
    build:
      context: .
      dockerfile: MCP/Dockerfile
    depends_on:
      - api
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:15
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=Password123
       - POSTGRES_DB=db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - app-network

volumes:
    db-data:
    
networks:
  app-network:
    driver: bridge
  
